version: '3.4'


services:
  bouvetassethubui:
    container_name: bouvetassethubui
    image: bouvetassethubui
    build:
      context: .
    ports:
      - 3000:3000
    stdin_open: true
    volumes: 
      - ./src:/app/src


