version: '3.4'

services:
   bouvet.assethub.api:
        image: ${DOCKER_REGISTRY-}bouvetassethubapi
        build:
            context: .
            dockerfile: Bouvet.AssetHub.API/Dockerfile
        networks:
            - asset-network 
        ports:
            - "80"
            - "3001:443"
networks:
    asset-network:
        external: true
