version: '3.4'

services:
    database:
        container_name: SqlServer
        image: mcr.microsoft.com/mssql/server:2019-latest
        user: root
        ports:
            - "1433:1433"
        volumes:
            - assethubcontext-vol:/var/opt/mssql
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=assethub1234@


    bouvet.assethub.ui:
        container_name: bouvetassethubui
        image: ${DOCKER_REGISTRY-}bouvetassethubui
        build:
            context: ./bouvet.assethub.ui
        ports:
            - 3000:3000
        stdin_open: true


    bouvet.assethub.api:
        container_name: bouvetassethubapi
        image: ${DOCKER_REGISTRY-}bouvetassethubapi
        environment: 
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_HTTPS_PORT=4000
            - ASPNETCORE_Kestrel__Certificates__Default__Password=HUB2022
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/assethubcert.pfx
        ports:
            - "80"
            - "4000:443"
        build:
            context: ./bouvet.assethub.server
            dockerfile: Bouvet.AssetHub.API/Dockerfile
        depends_on:
            - database
        volumes: 
            - ./bouvet.assethub.server/Certificates/https/:/https


volumes:
    assethubcontext-vol:
        external: true

