version: '3.4'

services:
    bouvet.assethub.api:
        image: ${DOCKER_REGISTRY-}bouvetassethubapi
        build:
            context: .
            dockerfile: Bouvet.AssetHub.API/Dockerfile
        networks:
            - asset-network 
        

networks:
    asset-network:
        external: true
